### ISSUE TITLE
Cell separator character escaping support

### ISSUE THREAD

**Issue by bot960528** [darkriszty/MarkdownTablePrettify-VSCodeExt#11]
sorry my english is not good.
The following translations come from google translation.
I find a problem.

    x|y|x&y|x\|y
    -|-|-|-
    `true` | `true`  | `true`  | `true`
    `true` | `false` | `false` | `true`
    `true` | `null`  | `null`  | `null`
    `false`| `true`  | `false` | `true`
    `false`| `false` | `false` | `false`
    `false`| `null`  | `false` | `null`
    `null` | `true`  | `null`  | `true`
    `null` | `false` | `false` | `null`
    `null` | `null`  | `null`  | `null`

If there are "Data Link Escape Character" in the table.Can not be properly identified and formatted.
for example ,In the first line “\\|”.

**Comment by darkriszty** [comment]
Thanks for reporting. I didn't think to add escaping the table cell separators, so it is currently something that is not supported. 
As a workaround you can use a different character, and replace it with "|" after the formatting.

**Comment by darkriszty** [comment]
I tried including this in the last release, but the implementation was not as trivial as I expected. So it will have to wait for v2.1 release.

**Comment by LeviticusMB** [comment]
Note: The correct (and most compatible) way to include the pipe character in a table is to use an HTML character entity (`&#x7c;` or `&#124;`).

**Comment by bschlenk** [comment]
Github supports escaping pipes with backslash: https://github.github.com/gfm/#example-193
So ideally this should support it.

**Comment by darkriszty** [comment]
Included in v2.0.0
