### ISSUE TITLE
Formatting requires a filename

### ISSUE THREAD

**Issue by brianary** [darkriszty/MarkdownTablePrettify-VSCodeExt#22]
#### Observed Behavior

1. File → New File
2. Change Language Mode to Markdown
3. Add and select a table
4. Right-click: no formatting options exist
5. Save file with a `.md` extension
6. Right-click selected table: formatting options now exist

#### Expected Behavior

Formatting options should exist in step 4 above, as well as step 6.

**Comment by darkriszty** [comment]
Hi @brianary 
This should work now from version 2.2.0.
