### ISSUE TITLE
Stop notification "Can't parse table from invalid text."

### ISSUE THREAD

**Issue by yaagma** [darkriszty/MarkdownTablePrettify-VSCodeExt#28]
The notification "Can't parse table from invalid text." is very annoying and appears frequently.
It appears even when there are no tables in the document.
¿Is there a setting in the extension to turn it off?

Thanks for this GREAT extension.
Raúl

**Comment by darkriszty** [comment]
I will add a configuration possibility to turn off these messages. 
Thanks for the suggestion!

**Comment by darkriszty** [comment]
In version 2.4.0 of the extension (it was just published) you're now able to turn off these messages by putting the following configuration in your `settings.json` file: 
`"markdownTablePrettify.showWindowMessages": false`
