### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by thaenalpha** [darkriszty/MarkdownTablePrettify-VSCodeExt#30]
[darkriszty.markdown-table-prettify-unresponsive.cpuprofile.txt](https://github.com/darkriszty/MarkdownTablePrettify-VSCodeExt/files/4323034/darkriszty.markdown-table-prettify-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `markdown-table-prettify`
- Extension Version: `2.4.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.43.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\n***\darkriszty.markdown-table-prettify-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by darkriszty** [comment]
Hi @thaenalpha 

I had a look in the CPU profile you uploaded but it didn't reveal too much. 

I'm guessing that you tried to format a large markdown file, as I know that this causes high CPU and takes time depending on the size of the file. 
Nevertheless, could you please let me know what were the circumstances around the high CPU load you experienced? For instance, if it was a big file, how big?

**Comment by thaenalpha** [comment]
Thank you for your response! This has inspired me :)
