### ISSUE TITLE
Provide command to run alongside prettier

### ISSUE THREAD

**Issue by tekumara** [darkriszty/MarkdownTablePrettify-VSCodeExt#40]
I use [prettier](https://prettier.io/) as my default markdown formatter, but it doesn't format tables nicely like this does!

Unfortunately  when prettier is the default formatter I can't seem to run  MarkdownTablePrettify.

Is there a way to run MarkdownTablePrettify via a vscode command, or some option other than setting it as the default formatter ?

**Comment by darkriszty** [comment]
Hi, at the moment there is no command available, as I didn't think it would be necessary 🙂 I guess that executing multiple formatters sequentially could also be a nice feature to add to VSCode.
Nevertheless, it shouldn't be too hard to implement a couple of custom commands for formatting the selection and formatting the entire document in my extension. I will try to implement this and include it in the next release.

**Comment by tekumara** [comment]
That would be awesome! I've just discovered the "Format Document With..." command, which might actually work for now.

**Comment by darkriszty** [comment]
Hi, the new version of the extension that got released today contains the command `Prettify markdown tables` that formats the current document. The keyboard shortcut CTRL + ALT + M is also assigned to this by default.

**Comment by tekumara** [comment]
Fantastic thank you @darkriszty ! 🙇‍♂️
