### ISSUE TITLE
Dockerfile improvements

### ISSUE THREAD

**Issue by slmg** [darkriszty/MarkdownTablePrettify-VSCodeExt#50]
As discussed in #32, here are my consumer feedbacks. :slightly_smiling_face: 

I noticed a few problems with the current Docker image:

#### Immutability

`node:current` is not an immutable tag, which does not guaranty a specific node version: `current` now points to `v15.5` whilst the shipped node in `darkrszty:latest` is on `v14.3`.

#### Size

The resulting image is about 1GB, which takes a substantial time to be pulled in CI (Github Action does not do any caching).
This is because `node:current` uses [`buildpack:stretch`](https://github.com/docker-library/buildpack-deps/blob/65d69325ad741cea6dee20781c1faaab2e003d87/debian/stretch/Dockerfile) base image, which is quite big. In addition `stretch` is getting deprecated, so probably not the ideal OS choice.

#### Build output

Neither the `node_modules/` directory nor the source typescripts code need to be shipped. Only the resulting compiled code is necessary to run the app. This can be solved via a multi-stage build.

**Comment by slmg** [comment]
#51 was created to address this issue. The resulting image is about 0.1GB. :+1:

**Comment by darkriszty** [comment]
Thanks for improving the dockerfile! I will merge your changes and push a new image.

**Comment by darkriszty** [comment]
Image with tag 3.2.1 should now be available.
