### ISSUE TITLE
The docker tag latest is not pointing to the latest pushed image

### ISSUE THREAD

**Issue by slmg** [darkriszty/MarkdownTablePrettify-VSCodeExt#52]
Hi @darkriszty,

Here is another issue about Docker :slightly_smiling_face:.

In the [registry](https://hub.docker.com/r/darkriszty/prettify-md/tags?page=1&ordering=last_updated), `latest` is currently mapped to the digest `2b5b9cea6e8f`, which is associated with version `3.0.0` instead of the current `3.2.1` (which digest is `f6900794e95f`).

Could you please fix this by running

```sh
docker image pull darkriszty/prettify-md:3.2.1
docker image tag darkriszty/prettify-md:3.2.1 darkriszty/prettify-md:latest
docker image push darkriszty/prettify-md:latest
```

Thank you.

**Comment by darkriszty** [comment]
Hi, thanks for pointing it out 👍 It should be updated now.
