### ISSUE TITLE
Open VSX

### ISSUE THREAD

**Issue by noraj** [darkriszty/MarkdownTablePrettify-VSCodeExt#59]
Hi can you push your extension to https://open-vsx.org/ in addition to VSCode Market Place so people using the FLOSS version could install it too?

I wrote [an article](https://blog.raw.pm/en/FLOSS-version-of-vscode-and-extensions-gallery/) on the subject.

**Comment by darkriszty** [comment]
Hi, I was waiting for a new release as the opportunity to publish the extension to OVSX 🙂 
Now it's ready and installable, I'm just waiting for the namespace to be claimed/verified. 

Extension: https://open-vsx.org/extension/darkriszty/markdown-table-prettify
Issue to remove namespace warning: https://github.com/EclipseFdn/open-vsx.org/issues/630

**Comment by darkriszty** [comment]
I'm closing this issue now. In case you notice any problems feel free to re-open it or create a new one.

**Comment by noraj** [comment]
Awesome, thanks.
