### ISSUE TITLE
No change to table in markdown...

### ISSUE THREAD

**Issue by FrancisVila** [darkriszty/MarkdownTablePrettify-VSCodeExt#64]
In my .md file, I selected a table > right click > "**Format Document**", and nothing happened.
I also tried "**Format document with...**" > "**Markdown Table Prettifier**" and nothing. 
![image](https://user-images.githubusercontent.com/23334974/144586287-50ad20f2-203a-485a-915a-820e97e31ac7.png)
![image](https://user-images.githubusercontent.com/23334974/144586340-bf4f612b-5542-4849-bc9c-9639c95455d2.png)

**Comment by darkriszty** [comment]
Hi @FrancisVila, I think it is because you have extra empty lines between each of the table rows. Just remove the empty lines so it can get recognized as a markdown table. 

Please let me know if that fixes the problem.

**Comment by FrancisVila** [comment]
Yes that does work, thank you!
