### ISSUE TITLE
Add as pre-commit

### ISSUE THREAD

**Issue by majulahsingapuri** [darkriszty/MarkdownTablePrettify-VSCodeExt#65]
Hi is it possible to configure this to run as a pre-commit hook using [pre-commit](https://pre-commit.com)?

**Comment by darkriszty** [comment]
Hi, I'm not using pre-commit hooks in general, but I'd assume it's just a command that you run before a commit, and then it should be possible to use this extension, given that it can also behave as a command. You could install the NPM package and use it from your pre-commit scripts by passing the *.MD files about to be committed.

- Install as a global package: `npm install -g markdown-table-prettify`
- In the pre-commit script for each *.MD file do:  `markdown-table-prettify < input.md > temp.md && cp temp.md input.md && rm temp.md` #_redirecting directly to input.md empties the file first, so a temp file could be used as a workaraound_

Hope this helps. Feel free to open an issue if you encounter any bugs.
