### ISSUE TITLE
Auto-select current table + format all tables

### ISSUE THREAD

**Issue by LeviticusMB** [darkriszty/MarkdownTablePrettify-VSCodeExt#7]
There is another Markdown table formatter, https://marketplace.visualstudio.com/items?itemName=shuworks.vscode-table-formatter, that has the neat feature that you don't have to select the whole table to reformat it.

I'd really like to see something like that in this extension, because I like your formatting style better.

**Comment by darkriszty** [comment]
@LeviticusMB just to make sure that I understood correctly: do you mean like that [gif animation](https://raw.githubusercontent.com/shuGH/vscode-table-formatter/master/res/complex_demo.gif) on the home page of the linked extension?

**Comment by LeviticusMB** [comment]
Yes, the ability to format the current table (and all tables in the document), without having to select them first would be awesome.

(Don't change the formatting code though! I like yours better. 😄)

**Comment by darkriszty** [comment]
Hi @LeviticusMB 
I finally found the time to work on this issue. This should work now from version 2.3.0.
