### ISSUE TITLE
Allow usage of tabs instead of spaces.

### ISSUE THREAD

**Issue by rokejulianlockhart** [darkriszty/MarkdownTablePrettify-VSCodeExt#72]
All of my Markdown documents use tabs for indentation. This is *especially* important for *tables* because

if my tables are formatted as https://github.com/darkriszty/MarkdownTablePrettify-VSCodeExt currently wants them to be

```
type   | data
-------|-------
author | @roke
tags   | #story
```

if I convert/view my `.md` file to/as a `.tsv` file temporarily,

![image](https://github.com/darkriszty/MarkdownTablePrettify-VSCodeExt/assets/42837531/7f2b5659-83aa-4dee-8976-66dd0d1addcb)

is how it appears in `code-insiders`, whereas

```
type   | data
-------|-------
author | @roke
tags   | #story
```

appears as

![image](https://github.com/darkriszty/MarkdownTablePrettify-VSCodeExt/assets/42837531/4f5bfb4f-8524-44a4-8624-5c80db85d83e)

thus saving space *and allowing instant transferral to speadsheet files of any format* (due to its standard format) if merely the `-|-` section is removed.

Unfortunately copying and pasting `.tsv`-ified `.md` tables with https://github.com/darkriszty/MarkdownTablePrettify-VSCodeExt automatically converts them to space-delimited versions. Please remediate this.

**Comment by RokeJulianLockhart** [comment]
@darkriszty, thanks for the in-depth evaluation. Some years later, I am glad to inform you that I consider this request to be moronic, too.
